/* Generated by Yosys 0.57+218 (git sha1 7ebd97216, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module dff_const2(clk, reset, q);
  input clk;
  wire clk;
  input reset;
  wire reset;
  output q;
  wire q;
  assign q = 1'h1;
endmodule
