/* Generated by Yosys 0.57+218 (git sha1 7ebd97216, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module dff_const3(clk, reset, q);
  input clk;
  wire clk;
  input reset;
  wire reset;
  output q;
  reg q;
  reg q1;
  always @(posedge clk, posedge reset)
    if (reset) q <= 1'h1;
    else q <= q1;
  always @(posedge clk, posedge reset)
    if (reset) q1 <= 1'h0;
    else q1 <= 1'h1;
endmodule
