/* Generated by Yosys 0.57+218 (git sha1 7ebd97216, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module opt_check4(a, b, c, y);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  output y;
  wire y;
  wire _0_;
  wire _1_;
  wire _2_;
  sky130_fd_sc_hd__xnor2_1 _3_ (
    .A(_1_),
    .B(_0_),
    .Y(_2_)
  );
  assign _1_ = c;
  assign _0_ = a;
  assign y = _2_;
endmodule
